config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'mains#main'
  devise_for :users
  resources :users
  resources :posts
  resources :questions

  namespace :users do
    get 'login', to: 'sessions#new'
  end

  get 'rechner', to: 'questions#rechner'
  get 'index', to: 'questions#index'
  post 'rechner', to: 'questions#create'

  get 'mains/thank_you'
  get 'contact', to: 'mains#contact'
  get 'more', to: 'mains#more'
  get 'team', to: 'mains#team'
  get 'impressum', to: 'mains#impressum'
  post 'mains/contact_sent'

end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    include QuestionsHelper
    def index
        @questions = Question.all
    end

    def show
        @question = Question.find(params[:id])
        @durchschnittsentgeltRV_2019 = 38901
        puts "#{@durchschnittsentgeltRV_2019} -- !!"
        @hilfsvar1 = hilfsvar1(@question.rente_start, @question.rente_kinder) #rente_vwerwerbsjahre
        @hilfsvar2 = hilfsvar2(@question.rente_reg) #rente_vreg
        @hilfsvar3 = hilfsvar3(@question.rente_eink, @durchschnittsentgeltRV_2019) #rente_ventgeltpunkte
        @hilfsvar4 = hilfsvar4(@question.rente_dauer) #rente_VBisZurRente
        @hilfsvar5 = hilfsvar5(@hilfsvar4, @hilfsvar2) #rente_vAnpassung
        @hilfsvar6 = hilfsvar6(@question.rente_estimate, @hilfsvar1, @hilfsvar4, @hilfsvar2)
        @rente_jahrAktuell = Time.now.year.to_f
        @rente_heute = rente_heute(@hilfsvar2, @hilfsvar1, @hilfsvar3)
        @rente_fiktiv = rente_fiktiv(@hilfsvar6, @hilfsvar2, @hilfsvar1)
        @rente_notwendig = notwendiges_gehalt(@hilfsvar6, @durchschnittsentgeltRV_2019)
        @rente_notwendigJahre = notwendige_jahre(@question.rente_estimate, @hilfsvar3, @hilfsvar2)
        @rente_hochrechnung = hochrechnung(@rente_heute, @hilfsvar3, @hilfsvar2, @hilfsvar4)
        @rente_hochrechnungMitAnpassung = hochrechnungMitAnpassung(@rente_heute, @hilfsvar3, @hilfsvar5)
    end

    def rechner
        @question = Question.new
    end

    def create
        testvar = params[:rente_jobs]
        puts "#{testvar}"
        temparray = []
        params[:rente_jobs].values.each.with_index do |val, index|
            puts "test #{index}, #{val}"
            temparray << ["#{val["beginn"]}, #{val["ende"]}, #{val["brutto"]}"]
        end
        @questions = Question.new(questions_params)
        @questions.rente_jobs = temparray
        if @questions.save
            flash[:success] = "Questions were okay"
            redirect_to question_url(@questions)
        else
            render 'rechner'
        end
        # byebug
    end

    def new
        @questions = Question.new
    end

    def update
    end

    def destroy
    end

    private
        def questions_params
            params.require(:question).permit(
                :rente_estimate, 
                :rente_art,
                :rente_zusatz, 
                :rente_start,  
                :rente_dauer, 
                :rente_eink, 
                :rente_reg,
                :rente_kinder, 
                :rente_betrieb, 
                :rente_wunschalter,
                :rente_jobs => [
                    :start => [],
                    :ende => [],
                    :brutto => [],
                ],
                :rente_kinder_gebjahr => [],
                photos: {
                    photo: {
                    }
                }
            )
            # params.permit(:beginn, :ende, :art, :brutto)
            # params.require(:question).permit(:rente_kinder_ges, rente_kinder_ges: [])
        end
end

app/helpers/questions_helper.rb
module QuestionsHelper

    def job_params
        params[:rente_jobs].values.each.with_index do |val, index|
            puts "test #{index}, #{val}"
            temparray << ["#{val["beginn"]}, #{val["ende"]}, #{val["art"]}, #{val["brutto"]}"]
        end
    end

    # puts "#{rente_estimate}, #{rente_art}, #{rente_start}, #{rente_dauer}, #{rente_eink}, #{rente_reg}, #{rente_kinder}, #{rente_kinder_gebjahr}, #{rente_betrieb}"

    def hilfsvar1(rente_start, rente_kinder)
        rente_vwerwerbsjahre = Time.now.year.to_f - rente_start.to_f + (rente_kinder.to_f * 3)
        puts "Hilfsvariable 1) #{rente_vwerwerbsjahre}"
        return rente_vwerwerbsjahre
    end

    def hilfsvar2(rente_reg)
        rente_reg = rente_reg.to_f,

        if (rente_reg == 0 || rente_reg == 31.89)
            rente_vReg = 31.89
        else
            rente_vReg = 33.05
        end
        puts "Hilfsvariable 2) #{rente_vReg}"
        return rente_vReg
    end

    def hilfsvar3(rente_eink, durchschnittsentgeltRV)
        puts "Durchschnittsentgeld #{durchschnittsentgeltRV}"
        puts "rente_eink #{rente_eink}"
        rente_ventgeltpunkte = rente_eink.to_f.round(2) / durchschnittsentgeltRV.to_f
        puts "Hilfsvariable 3) #{rente_ventgeltpunkte}"
        return rente_ventgeltpunkte.round(2)
    end

    def hilfsvar4(rente_dauer)
        rente_dauer = rente_dauer.to_f
        rente_vBisZurRente = 67 - (Time.now.year.to_f + 1 - rente_dauer.to_f)
        return rente_vBisZurRente
    end

    def hilfsvar5(rente_vBisZurRente, rente_vReg)
        rente_vAnpassung = (rente_vReg * 1.01 ** rente_vBisZurRente) * rente_vBisZurRente
        return rente_vAnpassung.round(2)
    end

    def hilfsvar6( rente_estimate, rente_vwerwerbsjahre, rente_vBisZurRente, rente_vReg)
        rente_vBenoetigt = rente_estimate / (( rente_vwerwerbsjahre + rente_vBisZurRente) * rente_vReg )
        return rente_vBenoetigt.round(2)
    end

    def rente_heute(rente_vReg, rente_vwerwerbsjahre, rente_ventgeltpunkte)
        puts "Rente Entgeltpunkte #{rente_ventgeltpunkte.to_f}"
        puts "Rente VReg #{rente_vReg.to_f}"
        puts "Rente Erwerbsjahre #{rente_vwerwerbsjahre.to_f}"
        rente_vHeute = rente_ventgeltpunkte.to_f * rente_vReg.to_f.to_f * rente_vwerwerbsjahre.to_f
        return rente_vHeute.round(2)
    end

    def rente_fiktiv(rente_vBenoetigt, rente_vReg, rente_vwerwerbsjahre)
        rente_fiktiv = rente_vBenoetigt.to_f.round(2) * rente_vReg.to_f  * rente_vwerwerbsjahre.to_f.round(2)
        return rente_fiktiv.round(2)
    end

    def notwendiges_gehalt(rente_vBenoetigt, durchschnittsentgeltRV)
        rente_notwendig = durchschnittsentgeltRV.to_f * rente_vBenoetigt.to_f
        return rente_notwendig
    end

    def notwendige_jahre(rente_estimate, rente_ventgeltpunkte, rente_vReg)
        rente_notwendigJahre = rente_estimate.to_f.round(2) / (rente_ventgeltpunkte.to_f.round(2) * rente_vReg.to_f.round(2))
        return rente_notwendigJahre.round(2)
    end

    def hochrechnung(rente_heute, rente_ventgeltpunkte, rente_vReg, rente_vBisZurRente)
        rente_hochrechnung = rente_heute.to_f.round(2) + (rente_ventgeltpunkte.to_f.round(2) * rente_vReg.to_f * rente_vBisZurRente.to_f)
        return rente_hochrechnung.round(2)
    end

    def hochrechnungMitAnpassung(rente_heute, rente_ventgeltpunkte, rente_vAnpassung)
        puts "Hochrechnung Mit Anpassung: "
        puts "rente_heute: #{rente_heute}"
        puts "ventgeld: #{rente_ventgeltpunkte}"
        puts "vanpassung: #{rente_vAnpassung}"
        rente_hochrechnungMitAnpassung = rente_heute.to_f.round(2) + (rente_ventgeltpunkte.to_f.round(2) * rente_vAnpassung.to_f.round(2))
        puts "Rente_HochrechnungMitAnpassung #{rente_hochrechnungMitAnpassung}"
        return rente_hochrechnungMitAnpassung.round(2)
    end

end

app/views/questions/index.html.erb
<div class="main_container">
    <%= render 'shared/title', title: "Fragebogen Übersicht" %>
    <div class="content_container">
        <% @questions.each do |question| %>

            <ul>
                <li><%= question.rente_estimate %></li>
                <li><%= question.rente_art %></li>
                <li><%= question.rente_start %></li>
                <li><%= question.rente_dauer %></li>
                <li><%= question.rente_eink %></li>
                <li><%= question.rente_reg %></li>
                <li><%= question.rente_kinder %></li>
                <li><%= question.rente_kinder_gebjahr %></li>
                <li><%= question.rente_betrieb %></li>
            </ul>

        <% end %>
    </div>
</div>



app/views/questions/rechner.html.erb
<%= javascript_pack_tag 'questions', 'calendar' %>
<%= yield :page_scripts %>

<div class="main_container">
  <%= render 'shared/title', title: "Rentenrechner" %>
  <div class="content_container">
    <%= form_with(model: @question, url: questions_path(@question), class: "form") do |f| %>
      <div class="form__item">
        <div class="form_itembox">
          <%= f.label :rente_estimate, "Wie hoch schätzen Sie Ihren monatlichen Bedarf als Rentner/in (Wohnungskosten, Versorgung, etc.)?", :class=> "form__label" %>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_estimate" %>
        </div>
        <div class="form__inputs">
          <%= f.text_field :rente_estimate, :class=>"form__input", :id=>"rente_estimate_input" %>
          <input type="range" min="100" max="5000" step="50" value="1000" class="slider" id="slider_r_estimate">
        </div>
      </div>
      <hr class="break">
      <div class="form__item">
        <div class="form_itembox">
          <p class="form__label">Welche Art von Beschäftigungsverhältnis liegt vor?</p>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_art" %>
        </div>
        <div class="form__inputs form__checkboxes">
          <%= f.label :rente_art, "abhängig beschäftigt", :value => "0", :class=> "checkbox__label" do %>abhängig beschäftigt
            <%= f.radio_button :rente_art, "abhängig beschäftigt", :checked => true, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
            <%= f.label :rente_art, "selbstständig", :value => "1", :class=> "checkbox__label" do %>selbstständig
              <%= f.radio_button :rente_art, "selbstständig", :checked => false, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
          </div>
      </div>

      <hr class="break">  <div class="form__item">
        <div class="form_itembox">
          <p class="form__label">Zahlen Sie aus den Einkünften aus selbstständiger Tätigkeit Beiträge in die private oder gesetzliche Rentenversicherung?</p>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_zusatz" %>
        </div>
        <div class="form__inputs form__checkboxes">
          <%= f.label :rente_zusatz, "Ich zahle keine Beiträge", :value => "0", :class=> "checkbox__label" do %>„Ich zahle keine Beiträge“
              <%= f.radio_button :rente_zusatz, "Ich zahle keine Beiträge", :checked => true, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
            <%= f.label :rente_zusatz, "gesetzlich", :value => "1", :class=> "checkbox__label" do %>gesetzlich
              <%= f.radio_button :rente_zusatz, "gesetzlich", :checked => false, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
            <%= f.label :rente_zusatz, "privat", :value => "2", :class=> "checkbox__label" do %>privat
              <%= f.radio_button :rente_zusatz, "privat", :checked => false, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
          </div>
      </div>

      <hr class="break">

      <div class="form__item">
        <div class="form_itembox">
          <%= f.label :rente_start, "In welchem Jahr haben Sie das erste Mal gearbeitet?", :class=> "form__label" %>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_start" %>
        </div>
        <div class="form__inputs">
          <%= f.text_field :rente_start, :class=> "form__input" %>
        </div>
      </div>

      <hr class="break">

      <div class="form__item js-checkboxes">
        <div class="form_itembox">
          <p class="form__label">Haben Sie vor diesem Job schon anderweitig in einem abhängigen Beschäftigungsverhältnis gestanden?</p>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_uebergang" %>
        </div>
        <div class="form__inputs form__checkboxes">
          <label class="checkbox__label" for="rente_uebergang_ja">Ja
            <input class="radiobutton__input" type="radio" value="1">
              <span class="checkbox__click" id="rente_uebergang__ja">
                <span class="checkbox__tick"></span>
              </span>
            </label>
          <label class="checkbox__label" for="rente_uebergang_nein">Nein
            <input class="radiobutton__input" type="radio" value="0">
              <span class="checkbox__click" id="rente_uebergang__nein">
                <span class="checkbox__tick"></span>
              </span>
            </label>
        </div>
      </div>

      <div class="form__item form__item--column" id="rente_jobs">
        <div>
          <%= f.label :rente_jobs, :class=> "form__label" do %>
            Für die Genauigkeit der Rentenberechnung ist es hilfreich Ihre Erwerbshistorie nachzuzeichnen. 	Bitte füllen Sie aus wie lange Sie zu welchen Bedingungen gearbeitet haben.
            <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_jobs" %>
          <% end %>
          <div class="form_itembox">
            
          </div>
        </div>
          <div class="form__box" id="rente__jobs">
            <div class="form__grid">
                <%= f.text_field :rente_jobs, multiple: true, :class=> "form__input", :placeholder => "Beginn", name: "rente_jobs[0][beginn]" %>
                <%= f.text_field :rente_jobs, multiple: true, :class=> "form__input", :placeholder => "Ende", name: "rente_jobs[0][ende]" %>
                <%= f.text_field :rente_jobs, multiple: true, :class=> "form__input", :placeholder => "Monatsbruttogehalt", name: "rente_jobs[0][brutto]" %>
                <div class="button js-delJob">
                  <div class="icon icon__small">
                    <div class="icon__delete"></div>
                  </div>
                </div>
            </div>
          </div>
          <div class="button js-addJobhistory">Job hinzufügen</div>
        </div>

      <hr class="break">
        <div class="form__item">
          <div class="form_itembox">
            <%= f.label :rente_dauer, "Welches Geburtsjahr?", :class=> "form__label" %>
            <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_dauer" %>
          </div>
          <div class="form__inputs">
            <%= f.text_field :rente_dauer, :class=> "form__input" %>
          </div>
        </div>

      <hr class="break">

      <div class="form__item">
        <div class="form_itembox">
          <%= f.label :rente_eink, "Wie hoch ist ihr Jahresbruttogehalt?", :class=> "form__label" %>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_eink" %>
        </div>
        <div class="form__inputs">
          <%= f.text_field :rente_eink, :class=> "form__input" %>
        </div>
      </div>

      <hr class="break">

      <div class="form__item">
        <div class="form_itembox">
          <p class="form__label">Leben Sie in Ost- oder Westdeutschland?</p>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_reg" %>
        </div>
        <div class="form__inputs form__checkboxes">
          <%= f.label :rente_reg, "Ostdeutschland", :value => "31.89", :class=> "checkbox__label" do %>Ostdeutschland
              <%= f.radio_button :rente_reg, "Ostdeutschland", :checked => true, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
            <%= f.label :rente_reg, "Westdeutschland", :value => "33.05", :class=> "checkbox__label" do %>Westdeutschland
              <%= f.radio_button :rente_reg, "Westdeutschland", :checked => false, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
          </div>
      </div>

      <hr class="break">

      <div class="form__item js-checkboxes">
        <div class="form_itembox">
          <p class="form__label">Haben Sie Kinder?</p>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_kinder__nachwuchs" %>
        </div>
        <div class="form__inputs form__checkboxes">
          <label class="checkbox__label" for="rente_kinder_ja">Ja
            <input class="radiobutton__input" type="radio" value="1">
              <span class="checkbox__click" id="rente_kinder__nachwuchs_ja">
                <span class="checkbox__tick"></span>
              </span>
            </label>
          <label class="checkbox__label" for="rente_kinder_nein">Nein
            <input class="radiobutton__input" type="radio" value="0">
              <span class="checkbox__click" id="rente_kinder__nachwuchs_nein">
                <span class="checkbox__tick"></span>
              </span>
            </label>
        </div>
      </div>


      <div class="form__item" id="rente__kinder">
        <div class="form_itembox">
          <%= f.label :rente_kinder, "Wie viele Kinder haben Sie?", :class=> "form__label" %>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_kinder" %>
        </div>
        <div class="form__inputs">
          <%= f.text_field :rente_kinder, :class=> "form__input", :value=> "0" %>
          <input type="range" min="1" max="5" step="1" value="1" class="slider" id="slider_r_kinder">
        </div>
      </div>

      <div class="form__item" id="rente__kinder_gebjahr">
        <%= f.label :rente_kinder_gebjahr, "In welchem Jahr geboren?", :class=> "form__label" %>
        <div class="form__inputs form__box" id="rente_kinderlist">
          <%= f.text_field :rente_kinder_gebjahr, multiple: true, :class=> "form__input", :placeholder => "1. Kind" %>
        </div>
      </div>

      <hr class="break">

      <div class="form__item">
        <div class="form_itembox">
          <p class="form__label">Haben Sie sich für eine betriebliche Rente qualifiziert (z.B. VBL)?</p>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_betrieb" %>
        </div>
        <div class="form__inputs form__checkboxes">
          <%= f.label :rente_betrieb, "Ja", :value => "1", :class=> "checkbox__label" do %>Ja
            <%= f.radio_button :rente_betrieb, "Ja", :checked => true, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
            <%= f.label :rente_betrieb, "Nein", :value => "0", :class=> "checkbox__label" do %>Nein
              <%= f.radio_button :rente_betrieb, "Nein", :checked => false, :class => "radiobutton__input" %>
              <span class="checkbox__click">
                <span class="checkbox__tick"></span>
              </span>
            <% end %>
          </div>
        </div>

      <hr class="break">

      <div class="form__item">
        <div class="form_itembox">
          <%= f.label :rente_wunschalter, "In welchem Alter möchten Sie in Rente gehen?", :class=> "form__label" %>
          <%= render 'shared/icons/icon-help', tooltip: "icon-help__rente_wunschalter" %>
        </div>
        <div class="form__inputs">
          <%= f.text_field :rente_wunschalter, :class=> "form__input" %>
        </div>
      </div>
      <hr class="break">
      <%= f.submit "Zum Ergebnis", :class=> "form__submit button" %>

    <% end %>

    <!-- </dialog> -->


  </div>
</div>





app/views/questions/show.html.erb
<div class="main_container">
    <%= render 'shared/title', title: "Ergebnis" %>
    <div class="content_container">
        <h2 class="tooltippy" data-tippy-content="Tooltip">Show</h2>
        <ul>
            <li>Durchschnittsentgeld (<%= Time.now.year %>):<%= @durchschnittsentgeltRV_2019 %></li>
            <li>Estimate:<%= @question.rente_estimate %></li>
            <li>Art:<%= @question.rente_art %></li>
            <li>Start:<%= @question.rente_start %></li>
            <li>Jobs:<%= @question.rente_jobs %></li>
            <li>Dauer:<%= @question.rente_dauer %></li>
            <li>Eink:<%= @question.rente_eink %></li>
            <li>Reg:<%= @question.rente_reg %></li>
            <li>Kinder:<%= @question.rente_kinder %></li>
            <li>Kinder_Gebjahr:<%= @question.rente_kinder_gebjahr %></li>
            <li>Betrieb:<%= @question.rente_betrieb %></li>
            <li>Wunschalter:<%= @question.rente_wunschalter %></li>
            <hr>
            <% @question.rente_jobs.each.with_index do |val, index| %></li>
                <li><%= index + 1 %>. Job:<%= val %></li>
            <% end %>
            <hr>
        </ul>
        <p>Hilfsvariable 1: <%= @hilfsvar1 %>  (rente_vwerwerbsjahre) </p>
        <p>Hilfsvariable 2: <%= @hilfsvar2 %>  (rente_vreg)</p>
        <p>Hilfsvariable 3: <%= @hilfsvar3 %> (rente_ventgeltpunkte)</p>
        <p>Hilfsvariable 4: <%= @hilfsvar4 %> (rente_VBisZurRente )</p>
        <p>Hilfsvariable 5: <%= @hilfsvar5 %> (rente_vAnpassung )</p>
        <p>Hilfsvariable 6: <%= @hilfsvar6 %> (rente_vBenoetigt )</p>
        <br>
        <p>Rente = Erwerbspunkte (EP) * Rentenwert (RW) * Erwerbsjahre</p>
        <p>(1/3) Formel für Rentenberechnung</p>
        <p>Rente heute = VEntgeltpunkte*Vreg*VErwerbsjahre = <%= @rente_heute %></p>
        <p>(2/3) Formel für Hochrechnung</p>
        <p>Hochrechnung = Rente heute + VEntgeltpunkte*Vreg* VbiszurRente = <%= @rente_hochrechnung %></p>
        <p>Hochrechnung mit Rentenanpassung= Rente heute + (VEntgeltpunkte * VAnpassung) = <%= @rente_hochrechnungMitAnpassung %></p>
        <p>Fiktive Rente = VBenötigt*Vreg*VErwerbsjahre = <%= @rente_fiktiv  %></p>
        <p>Notwendiges Gehalt = ((VBenötigt)*Jahresbrutto) = <%= @rente_notwendig %></p>
        <p>Notwendige Jahre = (Vestimate/(VEntgeltpunkte* Vreg)) = <%= @rente_notwendigJahre %></p>
    </div>

    <>
    <canvas
        id="myChart"
        class="chartjs"
        rente_hochrechnung="<%= @rente_hochrechnung %>"
        rente_hochrechnungMitAnpassung="<%= @rente_hochrechnungMitAnpassung %>"
        rente_VBisZurRente="<%= @hilfsvar4 %>"
        rente_fiktiv="<%= @rente_fiktiv  %>"
        rente_heute="<%= @rente_heute %>"
        rente_notwendigJahre="<%= @rente_notwendigJahre %>"
        rente_notwendigesGehalt="<%= @rente_notwendig %>"
        rente_jahrAktuell="<%= @rente_jahrAktuell %>"
    ></canvas>

    <canvas
        class="chartjs"
        id="myPieChart"
    ></canvas>

    <canvas
        class="chartjs"
        id="myPieChart2"
    ></canvas>

</div>
