config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'mains#main'
  devise_for :users
  resources :users
  resources :posts
  resources :questions

  namespace :users do
    get 'login', to: 'sessions#new'
  end

  get 'rechner', to: 'questions#rechner'
  get 'index', to: 'questions#index'
  post 'rechner', to: 'questions#create'

  get 'mains/thank_you'
  get 'contact', to: 'mains#contact'
  get 'more', to: 'mains#more'
  get 'team', to: 'mains#team'
  get 'impressum', to: 'mains#impressum'
  post 'mains/contact_sent'

end

app/views/layouts/_aironne.html.erb
<div class="calendar_button" id="calendar_but_prevmonth">Previous Month</div>
<div class="calendar_button" id="calendar_but_nextmonth">Next Month</div>
<div class="calendar_button" id="calendar_but_view4day">4 Days</div>
<div class="calendar_button" id="calendar_but_view4day_next">4 Days - Next</div>
<div class="calendar_button" id="calendar_but_view4day_prev">4 Days - Prev</div>


<div class="calendar"></div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <section class="footer content_container content_container--row ">
        <ul class="footer__item footer__item--icons">
            <li>
                <!-- Icon: Mail -->
                <svg class="footer__icon" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
                    <g>
                        <g>
                            <g>
                                <path d="M10.688,95.156C80.958,154.667,204.26,259.365,240.5,292.01c4.865,4.406,10.083,6.646,15.5,6.646     c5.406,0,10.615-2.219,15.469-6.604c36.271-32.677,159.573-137.385,229.844-196.896c4.375-3.698,5.042-10.198,1.5-14.719     C494.625,69.99,482.417,64,469.333,64H42.667c-13.083,0-25.292,5.99-33.479,16.438C5.646,84.958,6.313,91.458,10.688,95.156z"/>
                                <path d="M505.813,127.406c-3.781-1.76-8.229-1.146-11.375,1.542c-46.021,39.01-106.656,90.552-152.385,129.885     c-2.406,2.063-3.76,5.094-3.708,8.271c0.052,3.167,1.521,6.156,4,8.135c42.49,34.031,106.521,80.844,152.76,114.115     c1.844,1.333,4.031,2.01,6.229,2.01c1.667,0,3.333-0.385,4.865-1.177c3.563-1.823,5.802-5.49,5.802-9.49V137.083     C512,132.927,509.583,129.146,505.813,127.406z"/>
                                <path d="M16.896,389.354c46.25-33.271,110.292-80.083,152.771-114.115c2.479-1.979,3.948-4.969,4-8.135     c0.052-3.177-1.302-6.208-3.708-8.271C124.229,219.5,63.583,167.958,17.563,128.948c-3.167-2.688-7.625-3.281-11.375-1.542     C2.417,129.146,0,132.927,0,137.083v243.615c0,4,2.24,7.667,5.802,9.49c1.531,0.792,3.198,1.177,4.865,1.177     C12.865,391.365,15.052,390.688,16.896,389.354z"/>
                                <path d="M498.927,418.375c-44.656-31.948-126.917-91.51-176.021-131.365c-4-3.26-9.792-3.156-13.729,0.24     c-9.635,8.406-17.698,15.49-23.417,20.635c-17.563,15.854-41.938,15.854-59.542-0.021c-5.698-5.135-13.76-12.24-23.396-20.615     c-3.906-3.417-9.708-3.521-13.719-0.24c-48.938,39.719-131.292,99.354-176.021,131.365c-2.49,1.792-4.094,4.552-4.406,7.604     c-0.302,3.052,0.708,6.083,2.802,8.333C19.552,443.01,30.927,448,42.667,448h426.667c11.74,0,23.104-4.99,31.198-13.688     c2.083-2.24,3.104-5.271,2.802-8.323C503.021,422.938,501.417,420.167,498.927,418.375z"/>
                            </g>
                        </g>
                    </g>
                </svg>
            </li>
            <li>
                <!-- Icon: Facebook -->
                <svg class="footer__icon" role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <title>Facebook icon</title>
                    <path d="M23.9981 11.9991C23.9981 5.37216 18.626 0 11.9991 0C5.37216 0 0 5.37216 0 11.9991C0 17.9882 4.38789 22.9522 10.1242 23.8524V15.4676H7.07758V11.9991H10.1242V9.35553C10.1242 6.34826 11.9156 4.68714 14.6564 4.68714C15.9692 4.68714 17.3424 4.92149 17.3424 4.92149V7.87439H15.8294C14.3388 7.87439 13.8739 8.79933 13.8739 9.74824V11.9991H17.2018L16.6698 15.4676H13.8739V23.8524C19.6103 22.9522 23.9981 17.9882 23.9981 11.9991Z"/>
                </svg>
            </li>
        </ul>
        <div class="footer__item">
            <ul>
                <li><%= link_to 'Team', team_path, :class => 'link' %></li>
                <li><%= link_to 'Kontakt', contact_path, :class => 'link' %></li>
                <li><%= link_to 'Impressum', impressum_path, :class => 'link' %></li>
            </ul>
        </div>


        <ul class="footer__item">
            <%= image_pack_tag "Wirkungsschaffer_green_grey_screen.png", :class => 'footer__partner' %>
        </ul>
    </section>
    <section class="footer__copyright">
        <%= image_pack_tag "FinalIconTransparent.png", :class => 'footer__logo' %>
        <p><%= Time.now.year %> renteninfo</p>
    </section>

</footer>

app/views/layouts/_intro.html.erb

<div class="intro-slide">
  <!--<div class="intro-slide__buttonbox">
    <a class="link link--intro-slide" href="#"><h2>tool</h2></a>
    <a class="link link--intro-slide" href="#"><h2>blog</h2></a>

    <div class="intro-slide__hamburger">
      <div class="line line--intro-slide"></div>
      <div class="line line--intro-slide"></div>
      <div class="line line--intro-slide"></div>
    </div>
  </div> -->
  <div class="intro-slide__item active">
    <div class="mask"></div>
    <%= image_pack_tag "blonde-blur-casual-761977-700.jpg", :class => 'intro-slide__image' %>
    <div class="intro-slide__textbox">Deine Zukunft beginnt hier!</div>
  </div>
  <div class="intro-slide__item">
    <div class="mask"></div>
    <%= image_pack_tag "antique-encyclopedia-knowledge-24576-700.jpg", :class => 'intro-slide__image' %>
    <div class="intro-slide__textbox">Warum, was, wie?</div>
  </div>
  <div class="intro-slide__item">
    <div class="mask"></div>
    <%= image_pack_tag "opt_photo-of-person-using-laptop-700.jpg", :class => 'intro-slide__image' %>
    <div class="intro-slide__textbox">Rentenrechner</div>
  </div>
</div>

<!--<section class="sidebar">
  <%= link_to 'Home', root_path, :class => 'sidebar__element' %>
  <%= link_to 'Infos', posts_path, :class => 'sidebar__element' %>
  <%= link_to 'Online-Assistenten', rechner_path, :class => 'sidebar__element' %>
  <%= link_to 'Mehr erfahren', rechner_path, :class => 'sidebar__element' %>
  <%= link_to 'Impressum', impressum_path, :class => 'sidebar__element' %>
</section> -->

app/views/layouts/_mychart.html.erb
<canvas id="myChart" width="400" height="400"></canvas>

app/views/layouts/_nav.html.erb
<nav class="mynav">
    <div class="mynav_header">
        <div>
            <%= link_to image_pack_tag("FinalIconTransparent.png", class: "mynav__image", border: 0), root_path %>
        </div>
        <div class="mynav-item">
            <%= link_to 'Rentenrechner', rechner_path, :class => 'mynav__link' %>
        </div>
        <div class="mynav-item">
            <%= link_to 'Mehr erfahren', rechner_path, :class => 'mynav__link' %>
        </div>
        <div class="mynav-box"><% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>´s Profile<span class="caret"></span></a>
          <ul>
            <li><%= link_to "View your profile", user_path(current_user) %></li>
            <li><%= link_to "Edit your profile", edit_user_registration_path(current_user) %></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>

        <% end %></div>
    </div>

</nav>


<!--
<div class="nav_hamburger">
    <div class="line line--nav"></div>
    <div class="line line--nav"></div>
    <div class="line line--nav"></div>
</div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Renteninfo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-page="<%= @body_page_name %>">
    <%= render 'layouts/nav' %>

    <p id="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>